### ISSUE TITLE
Unable to resolve class org.h2.Driver

### ISSUE THREAD

**Issue by Michael-1** [jdurbin/durbinlib#8]
`./csvsql "select branding from supported_devices.csv"` returns:

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/mschmid/Downloads/durbinlib-master/scripts/csvsql: 4: unable to resolve class org.h2.Driver
 @ line 4, column 1.
   import org.h2.Driver
   ^

/Users/mschmid/Downloads/durbinlib-master/scripts/csvsql: 9: unable to resolve class Parser 
 @ line 9, column 10.
   parser = new Parser(description: '''
            ^

2 errors
```

`groovy --version` returns: 
```
Groovy Version: 2.4.5 JVM: 1.7.0_71 Vendor: Oracle Corporation OS: Mac OS X
```

**Comment by jdurbin** [comment]
Thanks for filing this report.   You're just not picking up any of the .jar library files.  If you do 

 ant localinstall

it should work for you. 

I changed the install process so that the default install does not copy the .jar files to ~/.groovy/lib/.  This was causing problems in some use cases.   Now, if you do "ant install" it just puts all the library jar files in 

 durbinlib/target/jars/

If you do 'ant install' to install, you will need to include these jar files in your classpath environment variable.   In bash:

export CLASSPATH=$CLASSPATH:"{pathtodurbinlib}/durbinlib/target/jar/*"

You can add this to your .bashrc/.bash_profile or other startup script.   This is probably the preferred installation mechanism.     I will update the documentation to reflect this installation change. 

Thanks again for calling my attention to this discrepancy with the documentation.
